# Position and orientation of the robot base wrt World
# it will be parsed in dual_ur_robotiq_rs.urdf.xacro
left_base_frame:
  x: 0.0
  y: 0.76
  z: 1.0
  roll: 0.0
  pitch: 0.0
  yaw: -1.57
right_base_frame:
  x: 0.0
  y: -0.76
  z: 1.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.57